import { useEffect, useState } from "react";
import { ArrowLeft, Building2, CalendarClock, Mail, MapPin, Phone, UserRound } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { coordinatorService } from "../../api/coordinatorService";
import { LoadingSpinner } from "../../components/common/LoadingSpinner";
import { useToast } from "../../context/ToastContext";

const fmt=(v,withTime=false)=>v?new Date(v).toLocaleString("en-GB",withTime?{dateStyle:"medium",timeStyle:"short"}:{dateStyle:"medium"}):"—";
const badge=(s)=>s==="Overdue"?"bg-red-100 text-red-700":s==="Follow-Up Completed"||s==="Converted"?"bg-emerald-100 text-emerald-700":"bg-orange-100 text-orange-700";
function Item({label,value}){return <div><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-sm text-slate-800">{value||"—"}</div></div>}

export function CoordinatorDetailsPage(){const {id}=useParams();const toast=useToast();const [row,setRow]=useState(null);const [loading,setLoading]=useState(true);useEffect(()=>{coordinatorService.get(id).then(x=>setRow(x.data)).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[id]);if(loading)return <LoadingSpinner label="Loading coordinator..."/>;if(!row)return <div>Coordinator not found.</div>;const history=[...(row.followUps||[])].sort((a,b)=>new Date(b.followUpDate)-new Date(a.followUpDate));return <div className="space-y-4">
 <div className="flex items-center gap-3"><Link to="/coordinators" className="rounded-lg border bg-white p-2 hover:bg-slate-50"><ArrowLeft size={18}/></Link><div><h1 className="text-lg font-bold text-slate-900">{row.coordinatorName}</h1><p className="text-xs text-slate-500">{row.schoolCourseName}</p></div><span className={`ml-auto rounded-full px-3 py-1 text-xs font-medium ${badge(row.followUpStatus)}`}>{row.followUpStatus}</span></div>
 {row.reminderActive&&<div className={`rounded-xl border p-4 text-sm ${row.followUpStatus==="Overdue"?"border-red-200 bg-red-50 text-red-800":"border-orange-200 bg-orange-50 text-orange-800"}`}><strong>Follow-up reminder:</strong> {row.followUpStatus==="Overdue"?`Action is ${Math.abs(row.daysRemaining)} days overdue.`:`Contact is required in ${row.daysRemaining} days.`}</div>}
 <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="mb-4 flex items-center gap-2 font-semibold"><Building2 size={17}/>Basic information</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Item label="Coordinator" value={row.coordinatorName}/><Item label="School / Course" value={row.schoolCourseName}/><Item label="Organization" value={row.organizationType}/><Item label="Contact person" value={row.contactPerson}/><Item label="Mobile" value={row.mobileNumber}/><Item label="Email" value={row.emailAddress}/><Item label="Location" value={row.location}/><Item label="Expected users" value={row.expectedUsers}/><Item label="Assigned team member" value={row.assignedTeamMember?.employeeName||"Unassigned"}/><Item label="Added date" value={fmt(row.addedDate)}/><Item label="Coordinator status" value={row.coordinatorStatus}/><Item label="Address" value={row.address}/><div className="sm:col-span-2 lg:col-span-3"><Item label="Notes" value={row.notes}/></div><div className="sm:col-span-2 lg:col-span-3"><Item label="Additional notes" value={row.additionalNotes}/></div></div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-semibold"><CalendarClock size={17}/>Follow-up summary</h2><div className="space-y-4"><Item label="5-month reminder" value={fmt(row.reminderStartDate)}/><Item label="6-month follow-up" value={fmt(row.sixMonthFollowUpDate)}/><Item label="Last contacted" value={fmt(row.lastFollowUpDate)}/><Item label="Next follow-up" value={fmt(row.nextFollowUpDate)}/><Item label="Time remaining" value={row.daysRemaining<0?`${Math.abs(row.daysRemaining)} days overdue`:`${row.daysRemaining} days remaining`}/></div></section></div>
 <section className="rounded-xl border bg-white p-5"><h2 className="mb-5 font-semibold">Follow-up timeline</h2><div className="relative ml-2 border-l-2 border-slate-200 pl-6"><div className="relative mb-7"><span className="absolute -left-[31px] top-1 h-3 w-3 rounded-full bg-indigo-500 ring-4 ring-indigo-50"/><div className="text-xs font-semibold text-indigo-600">{fmt(row.addedDate)}</div><div className="mt-1 text-sm font-medium">Coordinator added</div><p className="text-xs text-slate-500">Relationship tracking started by {row.createdBy?.employeeName||"Administrator"}.</p></div>{history.map(h=><article key={h.id||h._id} className="relative mb-7 last:mb-0"><span className="absolute -left-[31px] top-1 h-3 w-3 rounded-full bg-orange-500 ring-4 ring-orange-50"/><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-orange-600">{fmt(h.followUpDate,true)}</span><span className={`rounded-full px-2 py-0.5 text-[10px] ${badge(h.status)}`}>{h.status}</span></div><div className="mt-1 text-sm font-medium">{h.contactMethod} with {h.contactedPerson||"contact person"}</div><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{h.discussionDetails}</p>{h.requirementInterest&&<p className="mt-1 text-xs text-slate-500"><strong>Requirement / interest:</strong> {h.requirementInterest}</p>}{h.currentResponse&&<p className="mt-1 text-xs text-slate-500"><strong>Response:</strong> {h.currentResponse}</p>}{h.nextFollowUpDate&&<p className="mt-2 text-xs font-medium text-indigo-600">Next follow-up: {fmt(h.nextFollowUpDate)}</p>}<p className="mt-1 text-[10px] text-slate-400">Recorded by {h.recordedBy?.employeeName}; assigned to {h.assignedTeamMember?.employeeName||"Unassigned"}</p></article>)}{!history.length&&<p className="pb-2 text-sm text-slate-500">No follow-ups recorded yet.</p>}</div></section>
 </div>}
