import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { CalendarClock, ChevronLeft, ChevronRight, Eye, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { coordinatorService } from "../../api/coordinatorService";
import { LoadingSpinner } from "../../components/common/LoadingSpinner";
import { useToast } from "../../context/ToastContext";

const coordinatorStatuses=["Active","Inactive","On Hold","Converted"];
const followStatuses=["Upcoming","Reminder Started","Contact Pending","Contacted","Follow-Up Scheduled","Follow-Up Completed","Overdue","Not Interested","Converted","On Hold"];
const orgTypes=["School","College","Coaching Centre","Course Provider","Other"];
const empty={coordinatorName:"",schoolCourseName:"",organizationType:"School",contactPerson:"",mobileNumber:"",emailAddress:"",location:"",address:"",expectedUsers:"",notes:"",addedDate:new Date().toISOString().slice(0,10),coordinatorStatus:"Active",assignedTeamMemberId:"",additionalNotes:""};
const fmt=(v)=>v?new Date(v).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}):"—";
const statusStyle=(s)=>s==="Overdue"?"bg-red-100 text-red-700":s==="Follow-Up Completed"||s==="Converted"?"bg-emerald-100 text-emerald-700":s==="Reminder Started"||s==="Contact Pending"?"bg-orange-100 text-orange-700":"bg-slate-100 text-slate-700";

function Modal({title,onClose,children,wide=false}){return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/50 p-4"><div className={`max-h-[92vh] w-full ${wide?"max-w-5xl":"max-w-2xl"} overflow-y-auto rounded-2xl bg-white shadow-2xl`}><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4"><h2 className="font-semibold text-slate-900">{title}</h2><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X size={18}/></button></div>{children}</div></div>}
function Field({label,children,span=false}){return <label className={span?"md:col-span-2":""}><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span>{children}</label>}
const input="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";

export function CoordinatorsPage(){
 const toast=useToast();const [searchParams,setSearchParams]=useSearchParams();const [rows,setRows]=useState([]);const [meta,setMeta]=useState({page:1,totalPages:1,total:0});const [summary,setSummary]=useState({});const [employees,setEmployees]=useState([]);const [loading,setLoading]=useState(true);const [form,setForm]=useState(null);const [editing,setEditing]=useState(null);const [follow,setFollow]=useState(null);
 const query={page:searchParams.get("page")||1,limit:20,search:searchParams.get("search")||"",coordinatorStatus:searchParams.get("coordinatorStatus")||"",followUpStatus:searchParams.get("followUpStatus")||"",organizationType:searchParams.get("organizationType")||"",employeeId:searchParams.get("employeeId")||"",from:searchParams.get("from")||"",to:searchParams.get("to")||"",sortBy:searchParams.get("sortBy")||"addedDate",sortOrder:searchParams.get("sortOrder")||"desc"};
 const load=useCallback(async()=>{setLoading(true);try{const [list,sum,emps]=await Promise.all([coordinatorService.list(query),coordinatorService.summary(),coordinatorService.employees()]);setRows(list.data);setMeta(list.meta);setSummary(sum.data);setEmployees(emps.data);}catch(e){toast.error(e.message)}finally{setLoading(false)}},[searchParams.toString()]);
 useEffect(()=>{load()},[load]);
 const setQ=(key,value)=>{if(key==="sortOrder")return;const p=new URLSearchParams(searchParams);value?p.set(key,value):p.delete(key);if(key==="sortBy")p.set("sortOrder",query.sortBy===value&&query.sortOrder==="asc"?"desc":"asc");if(key!=="page")p.delete("page");setSearchParams(p)};
 const openEdit=(r)=>{setEditing(r);setForm({...empty,...r,addedDate:String(r.addedDate).slice(0,10),assignedTeamMemberId:r.assignedTeamMember?.employeeId||""})};
 const save=async(e)=>{e.preventDefault();try{editing?await coordinatorService.update(editing.id,form):await coordinatorService.create(form);toast.success(editing?"Coordinator updated":"Coordinator added");setForm(null);setEditing(null);load()}catch(err){toast.error(err.message)}};
 const remove=async(r)=>{if(!window.confirm(`Delete ${r.coordinatorName}? Follow-up history will also be removed.`))return;try{await coordinatorService.remove(r.id);toast.success("Coordinator deleted");load()}catch(e){toast.error(e.message)}};
 const sort=(key)=>{const p=new URLSearchParams(searchParams);p.set("sortBy",key);p.set("sortOrder",query.sortBy===key&&query.sortOrder==="asc"?"desc":"asc");p.delete("page");setSearchParams(p)};
 const cards=[['Total',summary.total,'',''],['Active',summary.active,'coordinatorStatus','Active'],['Upcoming',summary.upcoming,'followUpStatus','Reminder Started'],['Due in 30 days',summary.due,'followUpStatus','Follow-Up Scheduled'],['Overdue',summary.overdue,'followUpStatus','Overdue'],['Completed',summary.completed,'followUpStatus','Follow-Up Completed'],['Converted',summary.converted,'coordinatorStatus','Converted'],['On hold',summary.onHold,'coordinatorStatus','On Hold']];
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-lg font-bold text-slate-900">School / Course Coordinators</h1><p className="text-xs text-slate-500">Relationship tracking and continuous follow-up reminders</p></div><button onClick={()=>{setEditing(null);setForm({...empty})}} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700"><Plus size={16}/>Add coordinator</button></div>
  <div className="grid grid-cols-2 gap-2 lg:grid-cols-8">{cards.map(([label,value,key,status])=><button key={label} onClick={()=>key?setQ(key,status):setSearchParams(new URLSearchParams())} className={`rounded-xl border bg-white p-3 text-left shadow-sm ${key&&query[key]===status?"border-indigo-500 ring-2 ring-indigo-100":"border-slate-200"}`}><div className="text-[10px] uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-xl font-bold text-slate-900">{value||0}</div></button>)}</div>
  {summary.overdue>0&&<Link to="?followUpStatus=Overdue" className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800"><CalendarClock size={18}/><strong>Follow-up reminder:</strong> {summary.overdue} coordinator{summary.overdue===1?" is":"s are"} overdue. Immediate action is required.</Link>}
  <div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="grid gap-2 md:grid-cols-4 lg:grid-cols-8"><div className="relative md:col-span-2"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input className={`${input} pl-9`} placeholder="Search coordinator, school, contact..." value={query.search} onChange={e=>setQ("search",e.target.value)}/></div><select className={input} value={query.coordinatorStatus} onChange={e=>setQ("coordinatorStatus",e.target.value)}><option value="">All statuses</option>{coordinatorStatuses.map(x=><option key={x}>{x}</option>)}</select><select className={input} value={query.followUpStatus} onChange={e=>setQ("followUpStatus",e.target.value)}><option value="">All follow-ups</option>{followStatuses.map(x=><option key={x}>{x}</option>)}</select><select className={input} value={query.organizationType} onChange={e=>setQ("organizationType",e.target.value)}><option value="">All organizations</option>{orgTypes.map(x=><option key={x}>{x}</option>)}</select><select className={input} value={query.employeeId} onChange={e=>setQ("employeeId",e.target.value)}><option value="">All team members</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="date" title="Added from" className={input} value={query.from} onChange={e=>setQ("from",e.target.value)}/><input type="date" title="Added to" className={input} value={query.to} onChange={e=>setQ("to",e.target.value)}/></div></div>
  <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{loading?<LoadingSpinner label="Loading coordinators..."/>:<div className="overflow-x-auto"><table className="min-w-[1450px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{[['coordinatorName','Coordinator'],['schoolCourseName','School / Course'],['','Contact'],['addedDate','Added'],['','5-month reminder'],['sixMonthFollowUpDate','6-month follow-up'],['','Assigned to'],['','Last follow-up'],['nextFollowUpDate','Next follow-up'],['','Status'],['followUpStatus','Follow-up status'],['','Actions']].map(([key,label])=><th key={label} className="px-3 py-3 font-semibold"><button disabled={!key} onClick={()=>{setQ("sortBy",key);setQ("sortOrder",query.sortBy===key&&query.sortOrder==="asc"?"desc":"asc")}}>{label}</button></th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="px-3 py-3 font-semibold text-slate-900">{r.coordinatorName}</td><td className="px-3 py-3"><div>{r.schoolCourseName}</div><span className="text-[10px] text-slate-400">{r.organizationType}</span></td><td className="px-3 py-3"><div>{r.mobileNumber||"—"}</div><div className="text-slate-400">{r.emailAddress}</div></td><td className="px-3 py-3">{fmt(r.addedDate)}</td><td className="px-3 py-3">{fmt(r.reminderStartDate)}</td><td className="px-3 py-3">{fmt(r.sixMonthFollowUpDate)}</td><td className="px-3 py-3">{r.assignedTeamMember?.employeeName||"Unassigned"}</td><td className="px-3 py-3">{fmt(r.lastFollowUpDate)}</td><td className="px-3 py-3">{fmt(r.nextFollowUpDate)}</td><td className="px-3 py-3"><span className="rounded-full bg-blue-50 px-2 py-1 text-blue-700">{r.coordinatorStatus}</span></td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 ${statusStyle(r.followUpStatus)}`}>{r.followUpStatus}</span>{r.daysRemaining<0&&<div className="mt-1 text-[10px] text-red-600">{Math.abs(r.daysRemaining)} days overdue</div>}</td><td className="px-3 py-3"><div className="flex gap-1"><Link title="View" to={`/coordinators/${r.id}`} className="rounded p-1.5 hover:bg-indigo-50"><Eye size={15}/></Link><button title="Edit" onClick={()=>openEdit(r)} className="rounded p-1.5 hover:bg-indigo-50"><Pencil size={15}/></button><button title="Follow-up" onClick={()=>setFollow(r)} className="rounded p-1.5 hover:bg-orange-50"><CalendarClock size={15}/></button><button title="Delete" onClick={()=>remove(r)} className="rounded p-1.5 text-red-500 hover:bg-red-50"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!rows.length&&<div className="p-10 text-center text-sm text-slate-500">No coordinators match these filters.</div>}</div>}</div>
  <div className="flex items-center justify-between text-xs text-slate-500"><span>{meta.total||0} coordinators</span><div className="flex items-center gap-2"><button disabled={meta.page<=1} onClick={()=>setQ("page",meta.page-1)} className="rounded border p-1 disabled:opacity-30"><ChevronLeft size={16}/></button><span>Page {meta.page} of {meta.totalPages}</span><button disabled={meta.page>=meta.totalPages} onClick={()=>setQ("page",meta.page+1)} className="rounded border p-1 disabled:opacity-30"><ChevronRight size={16}/></button></div></div>
  {form&&<Modal title={editing?"Edit coordinator":"Add coordinator"} onClose={()=>setForm(null)}><form onSubmit={save} className="grid gap-4 p-5 md:grid-cols-2">{[["Coordinator name","coordinatorName","text",true],["School / Course name","schoolCourseName","text",true],["Contact person","contactPerson"],["Mobile number","mobileNumber"],["Email address","emailAddress","email"],["Location","location"],["Address","address"],["Number of students / expected users","expectedUsers","number"]].map(([label,key,type,req])=><Field key={key} label={label}><input required={req} type={type||"text"} className={input} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}<Field label="Organization type"><select required className={input} value={form.organizationType} onChange={e=>setForm({...form,organizationType:e.target.value})}>{orgTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Coordinator status"><select className={input} value={form.coordinatorStatus} onChange={e=>setForm({...form,coordinatorStatus:e.target.value})}>{coordinatorStatuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Coordinator added date"><input required type="date" className={input} value={form.addedDate} onChange={e=>setForm({...form,addedDate:e.target.value})}/></Field><Field label="Assigned team member"><select className={input} value={form.assignedTeamMemberId} onChange={e=>setForm({...form,assignedTeamMemberId:e.target.value})}><option value="">Unassigned</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field span label="Notes"><textarea className={input} rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><Field span label="Additional notes"><textarea className={input} rows="3" value={form.additionalNotes} onChange={e=>setForm({...form,additionalNotes:e.target.value})}/></Field><div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={()=>setForm(null)} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">{editing?"Save changes":"Add coordinator"}</button></div></form></Modal>}
  {follow&&<FollowUpModal coordinator={follow} employees={employees} onClose={()=>setFollow(null)} onSaved={()=>{setFollow(null);load()}} toast={toast}/>}</div>
}

function FollowUpModal({coordinator,employees,onClose,onSaved,toast}){const [f,setF]=useState({followUpDate:new Date().toISOString().slice(0,10),contactMethod:"Phone",contactedPerson:coordinator.contactPerson||coordinator.coordinatorName,discussionDetails:"",requirementInterest:"",currentResponse:"",status:"Contacted",nextFollowUpDate:"",assignedTeamMemberId:coordinator.assignedTeamMember?.employeeId||"",remarks:""});const save=async(e)=>{e.preventDefault();try{await coordinatorService.addFollowUp(coordinator.id,f);toast.success("Follow-up recorded");onSaved()}catch(err){toast.error(err.message)}};return <Modal title={`Record follow-up · ${coordinator.coordinatorName}`} onClose={onClose}><form onSubmit={save} className="grid gap-4 p-5 md:grid-cols-2"><Field label="Follow-up date"><input required type="date" className={input} value={f.followUpDate} onChange={e=>setF({...f,followUpDate:e.target.value})}/></Field><Field label="Contact method"><select className={input} value={f.contactMethod} onChange={e=>setF({...f,contactMethod:e.target.value})}>{["Phone","WhatsApp","Email","Meeting","Other"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Contacted person"><input className={input} value={f.contactedPerson} onChange={e=>setF({...f,contactedPerson:e.target.value})}/></Field><Field label="Follow-up status"><select className={input} value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{followStatuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Next follow-up date"><input type="date" className={input} value={f.nextFollowUpDate} onChange={e=>setF({...f,nextFollowUpDate:e.target.value})}/></Field><Field label="Assigned team member"><select className={input} value={f.assignedTeamMemberId} onChange={e=>setF({...f,assignedTeamMemberId:e.target.value})}><option value="">Unassigned</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>{[["Discussion details","discussionDetails",true],["Requirement / interest","requirementInterest"],["Current response","currentResponse"],["Remarks","remarks"]].map(([label,key,req])=><Field key={key} span label={label}><textarea required={req} rows="3" className={input} value={f[key]} onChange={e=>setF({...f,[key]:e.target.value})}/></Field>)}<div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">Save follow-up</button></div></form></Modal>}
