import { useEffect, useState } from "react";
import { Copy, Link2, Plus, Users } from "lucide-react";
import { affiliateMarketingService as api } from "../api/affiliateMarketingService";
import { useToast } from "../context/ToastContext";

const tabs = ["Dashboard", "Affiliates", "Referral Users", "Subscriptions", "Reports", "Notifications", "Settings"];
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value || 0));
export function AffiliateMarketingPage() {
  const toast = useToast(); const [tab, setTab] = useState("Dashboard"); const [data, setData] = useState({}); const [showCreate, setShowCreate] = useState(false);
  async function load() { try { const [dashboard, affiliates, referrals, purchases, settings] = await Promise.all([api.dashboard(), api.affiliates(), api.referrals(), api.purchases(), api.settings()]); setData({ dashboard: dashboard.data.data, affiliates: affiliates.data.data, referrals: referrals.data.data, purchases: purchases.data.data, settings: settings.data.data }); } catch (e) { toast.error(e.message); } }
  useEffect(() => { void load(); }, []);
  async function create(event) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api.create(values); setShowCreate(false); toast.success("Affiliate created"); void load(); } catch (e) { toast.error(e.message); } }
  async function status(item, value) { try { await api.update(item.id, { status: value }); toast.success(`Affiliate ${value.toLowerCase()}`); void load(); } catch (e) { toast.error(e.message); } }
  const cards = data.dashboard || {};
  return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-black">Affiliate Marketing</h1><p className="text-sm text-slate-500">Referral attribution, conversions and affiliate performance.</p></div><button onClick={() => setShowCreate(true)} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white"><Plus size={16}/>New Affiliate</button></div>
    <div className="flex gap-2 overflow-x-auto border-b">{tabs.map(x => <button key={x} onClick={() => setTab(x)} className={`whitespace-nowrap px-3 py-3 text-sm font-bold ${tab === x ? "border-b-2 border-indigo-600 text-indigo-700" : "text-slate-500"}`}>{x}</button>)}</div>
    {tab === "Dashboard" && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Affiliates",cards.totalAffiliates],["Active Affiliates",cards.activeAffiliates],["Referral Clicks",cards.clicks],["Registrations",cards.registrations],["Successful Purchases",cards.successfulPurchases],["Purchase Amount",money(cards.totalPurchaseAmount)],["Average Value",money(cards.averagePurchaseValue)],["Conversion Rate",`${Number(cards.conversionRate||0).toFixed(1)}%`]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5"><p className="text-2xl font-black">{value??0}</p><p className="text-sm text-slate-500">{label}</p></div>)}</div>}
    {tab === "Affiliates" && <Table headers={["Affiliate","Code","Contact","Status","Clicks","Registrations","Purchases","Amount","Action"]} rows={(data.affiliates||[]).map(x => [x.affiliateName,x.affiliateCode,<span>{x.email}<br/>{x.mobile}</span>,x.status,x.clicks,x.registrations,x.successfulPurchases,money(x.totalPurchaseAmount),<div className="flex gap-1"><button title="Copy link" onClick={()=>{navigator.clipboard.writeText(x.referralLink);toast.success("Link copied")}} className="border rounded p-1"><Copy size={14}/></button><select value={x.status} onChange={e=>status(x,e.target.value)} className="rounded border text-xs"><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></div>])}/>} 
    {tab === "Referral Users" && <Table headers={["Affiliate","Code","User ID","Platform","Clicked","Registered","Status"]} rows={(data.referrals||[]).map(x=>[x.affiliateId?.affiliateName,x.affiliateCode,x.userId||"—",x.platform,new Date(x.clickAt).toLocaleString(),x.registrationAt?new Date(x.registrationAt).toLocaleString():"—",x.conversionStatus])}/>} 
    {(tab === "Subscriptions" || tab === "Reports") && <Table headers={["Affiliate","User","Platform","Plan","Amount","Transaction","Gateway","Purchase Date","Status"]} rows={(data.purchases||[]).map(x=>[x.affiliateId?.affiliateName,x.userId,x.platform,x.planId,money(x.amount),x.transactionId,x.paymentGateway,new Date(x.purchaseAt).toLocaleString(),x.subscriptionStatus])}/>} 
    {tab === "Notifications" && <div className="rounded-2xl border bg-white p-8 text-center text-slate-500">Milestone notifications are generated automatically and protected against duplicates.</div>}
    {tab === "Settings" && data.settings && <form className="max-w-xl space-y-4 rounded-2xl border bg-white p-6" onSubmit={async e=>{e.preventDefault();try{await api.updateSettings(Object.fromEntries(new FormData(e.currentTarget)));toast.success("Settings saved");void load()}catch(err){toast.error(err.message)}}}><label className="block text-sm font-bold">Referral base URL<input name="referralBaseUrl" defaultValue={data.settings.referralBaseUrl} className="mt-1 w-full rounded-lg border p-2"/></label><label className="block text-sm font-bold">Attribution window (days)<input name="attributionWindowDays" type="number" defaultValue={data.settings.attributionWindowDays} className="mt-1 w-full rounded-lg border p-2"/></label><label className="block text-sm font-bold">Milestone count<input name="milestoneCount" type="number" defaultValue={data.settings.milestoneCount} className="mt-1 w-full rounded-lg border p-2"/></label><button className="rounded-lg bg-indigo-600 px-4 py-2 font-bold text-white">Save Settings</button></form>}
    {showCreate && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-4"><form onSubmit={create} className="grid max-h-[90vh] w-full max-w-xl grid-cols-2 gap-3 overflow-auto rounded-2xl bg-white p-6"><h2 className="col-span-2 text-xl font-black">Create affiliate</h2>{[["firstName","First name"],["lastName","Last name"],["affiliateName","Affiliate name"],["email","Email"],["mobile","Mobile"],["username","Username"],["password","Password"],["affiliateCode","Custom code (optional)"]].map(([name,label])=><label key={name} className="text-sm font-bold">{label}<input required={!['lastName','mobile','affiliateCode'].includes(name)} type={name==='password'?'password':name==='email'?'email':'text'} name={name} className="mt-1 w-full rounded-lg border p-2"/></label>)}<div className="col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setShowCreate(false)} className="rounded-lg border px-4 py-2">Cancel</button><button className="rounded-lg bg-indigo-600 px-4 py-2 font-bold text-white">Create</button></div></form></div>}
  </div>;
}
function Table({headers,rows}) { return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{headers.map(x=><th key={x} className="px-3 py-3 text-left">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className="whitespace-nowrap px-3 py-3 text-slate-700">{cell}</td>)}</tr>)}</tbody></table></div>}
