import { useEffect, useState } from "react";
import { Copy, Plus } from "lucide-react";
import { affiliateMarketingService as api } from "../api/affiliateMarketingService";
import { useToast } from "../context/ToastContext";

const tabs = ["Dashboard", "Affiliates", "Journeys", "Subscriptions", "Reports", "Settings"];
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value || 0));
const date = (value) => value ? new Date(value).toLocaleString() : "-";
const pick = (response) => response.data?.data ?? response.data;
export function AffiliateMarketingPage() {
  const toast = useToast(); const [tab, setTab] = useState("Dashboard"); const [data, setData] = useState({}); const [filters, setFilters] = useState({}); const [showCreate, setShowCreate] = useState(false);
  const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value));
  async function load() { try { const [dashboard, affiliates, referrals, purchases, settings] = await Promise.all([api.dashboard(params), api.affiliates(), api.referrals(params), api.purchases(params), api.settings()]); setData({ dashboard: pick(dashboard), affiliates: pick(affiliates), referrals: pick(referrals), purchases: pick(purchases), settings: pick(settings) }); } catch (e) { toast.error(e.message); } }
  useEffect(() => { void load(); }, []);
  useEffect(() => { void load(); }, [JSON.stringify(filters)]);
  async function applyFilters(event) { event.preventDefault(); setFilters(Object.fromEntries(new FormData(event.currentTarget))); }
  async function create(event) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api.create(values); setShowCreate(false); toast.success("Affiliate created"); void load(); } catch (e) { toast.error(e.message); } }
  async function status(item, value) { try { await api.update(item.id, { status: value }); toast.success(`Affiliate ${value.toLowerCase()}`); void load(); } catch (e) { toast.error(e.message); } }
  const cards = data.dashboard || {};
  const referrals = data.referrals?.items || data.referrals || [];
  const purchases = data.purchases?.items || data.purchases || [];
  return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-black">Affiliate Marketing</h1><p className="text-sm text-slate-500">Referral journeys, attribution, conversions and commission.</p></div><button onClick={() => setShowCreate(true)} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white"><Plus size={16}/>New Affiliate</button></div>
    <form onSubmit={applyFilters} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4 xl:grid-cols-6"><input name="from" type="date" className="rounded border p-2 text-sm"/><input name="to" type="date" className="rounded border p-2 text-sm"/><select name="affiliateId" className="rounded border p-2 text-sm"><option value="">All affiliates</option>{(data.affiliates||[]).map(x=><option key={x.id} value={x.id}>{x.affiliateName}</option>)}</select><input name="campaign" placeholder="Campaign" className="rounded border p-2 text-sm"/>{["clickStatus","installationStatus","registrationStatus","loginStatus","purchaseStatus","conversionStatus","userType"].map(x=><input key={x} name={x} placeholder={x.replace(/[A-Z]/g," $&")} className="rounded border p-2 text-sm"/>)}<button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Apply</button></form>
    <div className="flex gap-2 overflow-x-auto border-b">{tabs.map(x => <button key={x} onClick={() => setTab(x)} className={`whitespace-nowrap px-3 py-3 text-sm font-bold ${tab === x ? "border-b-2 border-indigo-600 text-indigo-700" : "text-slate-500"}`}>{x}</button>)}</div>
    {tab === "Dashboard" && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Affiliates",cards.totalAffiliates],["Active Affiliates",cards.activeAffiliates],["Total Clicks",cards.totalClicks],["Unique Clicks",cards.uniqueClicks],["New Installs",cards.newAppInstallations],["Existing App Users",cards.existingAppUsers],["Registrations",cards.registrations],["Existing Logins",cards.existingUserLogins],["Premium Purchases",cards.premiumPurchases],["Successful Conversions",cards.successfulConversions],["Pending Conversions",cards.pendingConversions],["Failed/Cancelled",cards.failedOrCancelledPurchases],["Purchase Amount",money(cards.totalPurchaseAmount)],["Commission Earned",money(cards.commissionEarned)],["Conversion Rate",`${Number(cards.conversionRate||0).toFixed(1)}%`]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5"><p className="text-2xl font-black">{value??0}</p><p className="text-sm text-slate-500">{label}</p></div>)}</div>}
    {tab === "Affiliates" && <Table headers={["Affiliate","Code","Contact","Status","Clicks","Conversions","Commission","Action"]} rows={(data.affiliates||[]).map(x => [x.affiliateName,x.affiliateCode,<span>{x.email}<br/>{x.mobile}</span>,x.status,x.totalClicks,x.successfulConversions,money(x.commissionEarned),<div className="flex gap-1"><button title="Copy link" onClick={()=>{navigator.clipboard.writeText(x.referralLink);toast.success("Link copied")}} className="border rounded p-1"><Copy size={14}/></button><select value={x.status} onChange={e=>status(x,e.target.value)} className="rounded border text-xs"><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></div>])}/>} 
    {(tab === "Journeys" || tab === "Reports") && <Table headers={["Affiliate","Click ID","Campaign","Journey","User","Clicked","Installed","Registered","Logged In","Purchase","Conversion","Commission"]} rows={referrals.map(x=>[x.affiliateId?.affiliateName,x.referralClickId,x.campaign||"-",`${x.clickStatus} -> ${x.installationStatus} -> ${x.registrationStatus} -> ${x.loginStatus} -> ${x.purchaseStatus}`,x.userId||"-",date(x.clickAt),date(x.firstAppOpenAt),date(x.registrationAt),date(x.loginAt),x.purchaseStatus,x.conversionStatus,money(x.commissionAmount)])}/>} 
    {tab === "Subscriptions" && <Table headers={["Affiliate","User","Platform","Plan","Amount","Commission","Transaction","Gateway","Purchase Date","Status"]} rows={purchases.map(x=>[x.affiliateId?.affiliateName,x.userId,x.platform,x.planId,money(x.amount),money(x.commissionAmount),x.transactionId,x.paymentGateway,date(x.purchaseAt),x.conversionStatus||x.subscriptionStatus])}/>} 
    {tab === "Settings" && data.settings && <form className="max-w-xl space-y-4 rounded-2xl border bg-white p-6" onSubmit={async e=>{e.preventDefault();try{await api.updateSettings(Object.fromEntries(new FormData(e.currentTarget)));toast.success("Settings saved");void load()}catch(err){toast.error(err.message)}}}><label className="block text-sm font-bold">Referral base URL<input name="referralBaseUrl" defaultValue={data.settings.referralBaseUrl} className="mt-1 w-full rounded-lg border p-2"/></label><label className="block text-sm font-bold">Attribution window (days)<input name="attributionWindowDays" type="number" defaultValue={data.settings.attributionWindowDays} className="mt-1 w-full rounded-lg border p-2"/></label><label className="block text-sm font-bold">Attribution model<select name="attributionModel" defaultValue={data.settings.attributionModel||"LAST_CLICK"} className="mt-1 w-full rounded-lg border p-2"><option>LAST_CLICK</option><option>FIRST_CLICK</option></select></label><label className="block text-sm font-bold">Commission rate (%)<input name="commissionRatePercent" type="number" step="0.01" defaultValue={data.settings.commissionRatePercent} className="mt-1 w-full rounded-lg border p-2"/></label><label className="flex items-center gap-2 text-sm font-bold"><input name="allowExistingUserAttribution" type="checkbox" value="true" defaultChecked={data.settings.allowExistingUserAttribution!==false}/>Attribute existing-user logins</label><label className="block text-sm font-bold">Milestone count<input name="milestoneCount" type="number" defaultValue={data.settings.milestoneCount} className="mt-1 w-full rounded-lg border p-2"/></label><button className="rounded-lg bg-indigo-600 px-4 py-2 font-bold text-white">Save Settings</button></form>}
    {showCreate && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-4"><form onSubmit={create} className="grid max-h-[90vh] w-full max-w-xl grid-cols-2 gap-3 overflow-auto rounded-2xl bg-white p-6"><h2 className="col-span-2 text-xl font-black">Create affiliate</h2>{[["firstName","First name"],["lastName","Last name"],["affiliateName","Affiliate name"],["email","Email"],["mobile","Mobile"],["username","Username"],["password","Password"],["affiliateCode","Custom code (optional)"]].map(([name,label])=><label key={name} className="text-sm font-bold">{label}<input required={!['lastName','mobile','affiliateCode'].includes(name)} type={name==='password'?'password':name==='email'?'email':'text'} name={name} className="mt-1 w-full rounded-lg border p-2"/></label>)}<div className="col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setShowCreate(false)} className="rounded-lg border px-4 py-2">Cancel</button><button className="rounded-lg bg-indigo-600 px-4 py-2 font-bold text-white">Create</button></div></form></div>}
  </div>;
}
function Table({headers,rows}) { return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{headers.map(x=><th key={x} className="px-3 py-3 text-left">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className="whitespace-nowrap px-3 py-3 text-slate-700">{cell}</td>)}</tr>)}</tbody></table></div>}
