import { http } from "./http";

const base = "/admin/national-competitions";

export const nationalCompetitionService = {
  dashboard: async () => (await http.get(`${base}/dashboard`)).data,
  calendar: async (params = {}) => (await http.get("/admin/national-competitions-calendar", { params })).data,
  list: async (params = {}) => (await http.get(base, { params })).data,
  get: async (id) => (await http.get(`${base}/${id}`)).data,
  preview: async (id) => (await http.get(`${base}/${id}/preview`)).data,
  create: async (payload) => (await http.post(base, payload)).data,
  update: async (id, payload) => (await http.put(`${base}/${id}`, payload)).data,
  duplicate: async (id) => (await http.post(`${base}/${id}/duplicate`)).data,
  remove: async (id) => (await http.delete(`${base}/${id}`)).data,
  setStatus: async (id, status) => (await http.patch(`${base}/${id}/status`, { status })).data,
  action: async (id, action) => (await http.patch(`${base}/${id}/status`, { action })).data,
  participants: async (id, params = {}) => (await http.get(`${base}/${id}/participants`, { params })).data,
  deviceLogs: async (id) => (await http.get(`${base}/${id}/device-logs`)).data,
  updateParticipant: async (registrationId, payload) => (await http.patch(`${base}/participants/${registrationId}`, payload)).data,
  leaderboard: async (id, params = {}) => (await http.get(`${base}/${id}/leaderboard`, { params })).data,
  leaderboardSnapshots: async (id) => (await http.get(`${base}/${id}/leaderboard/snapshots`)).data,
  rankingHistory: async (id) => (await http.get(`${base}/${id}/ranking-history`)).data,
  refreshLeaderboard: async (id) => (await http.post(`${base}/${id}/leaderboard/refresh`)).data,
  reports: async (id) => (await http.get(`${base}/${id}/reports`)).data,
  analytics: async (id) => (await http.get(`${base}/${id}/analytics`)).data,
  attendance: async (id) => (await http.get(`${base}/${id}/attendance`)).data,
  disqualified: async (id) => (await http.get(`${base}/${id}/disqualified`)).data,
  rewards: async (id) => (await http.get(`${base}/${id}/rewards`)).data,
  createReward: async (id, payload) => (await http.post(`${base}/${id}/rewards`, payload)).data,
  updateReward: async (rewardId, payload) => (await http.patch(`${base}/rewards/${rewardId}`, payload)).data,
  approveReward: async (rewardId, approvalStatus = "approved") => (await http.patch(`${base}/rewards/${rewardId}/approval`, { approvalStatus })).data,
  createVoucher: async (id, payload) => (await http.post(`${base}/${id}/vouchers`, payload)).data,
  distributePrizes: async (id) => (await http.post(`${base}/${id}/prize-distribution`)).data,
  notifications: async (id) => (await http.get(`${base}/${id}/notifications`)).data,
  createNotification: async (id, payload) => (await http.post(`${base}/${id}/notifications`, payload)).data,
  auditLogs: async (params = {}) => (await http.get("/admin/national-competitions-audit-logs", { params })).data,
  questionPoolMeta: async () => (await http.get(`${base}/question-pool/meta`)).data,
  questionPool: async (params = {}) => (await http.get(`${base}/question-pool`, { params })).data,
  exportUrl: (id, format = "excel") => `${http.defaults.baseURL}${base}/${id}/export/${format}`,
};
