import { useEffect, useState } from "react";
import { followUpService } from "../../api/followUpService";
import { useToast } from "../../context/ToastContext";
import { useAuth } from "../../context/AuthContext";
import { cn, ui } from "../../ui";

const statuses = ["Pending", "Progress", "Completed", "Cancelled"];
const fmt = (v) => v ? new Date(v).toLocaleString() : "—";
export function UserManagementPage() {
  const toast=useToast(); const {admin}=useAuth(); const employeeAccount=admin?.adminRole==="employee"; const [items,setItems]=useState([]); const [employees,setEmployees]=useState([]); const [meta,setMeta]=useState({page:1,totalPages:1}); const [loading,setLoading]=useState(true); const [detail,setDetail]=useState(null); const [assigning,setAssigning]=useState(null);
  const [filters,setFilters]=useState({name:"",email:"",examMode:"",plan:"",followUpStatus:"",employeeId:"",from:"",to:"",page:1,limit:20});
  const load=async(next=filters)=>{setLoading(true);try{const r=await followUpService.users(next);setItems(r.data||[]);setMeta(r.meta||{});}catch(e){toast.error(e.message)}finally{setLoading(false)}};
  useEffect(()=>{void load(); followUpService.employees().then(r=>setEmployees(r.data||[])).catch(()=>setEmployees([]));},[]);
  const set=(key,value)=>setFilters(f=>({...f,[key]:value,page:1}));
  const apply=(e)=>{e.preventDefault();void load({...filters,page:1})};
  const assign=async(user,employeeId)=>{if(!employeeAccount&&!employeeId)return;try{await followUpService.assign(user.id,employeeAccount?admin.id:employeeId);toast.success(employeeAccount?"User assigned to you":user.followUp?"Follow-up reassigned":"User added to follow-up");setAssigning(null);await load();}catch(e){toast.error(e.message)}};
  return <div className="space-y-5">
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4"><div className="text-[11px] font-black uppercase tracking-[.25em] text-sky-700">User Management</div><p className={ui.muted}>Registered frontend users and their employee follow-up assignment.</p></div>
      <form onSubmit={apply} className="grid gap-3 md:grid-cols-3 xl:grid-cols-5">
        <input className={ui.input} placeholder="User name" value={filters.name} onChange={e=>set("name",e.target.value)}/><input className={ui.input} placeholder="Email" value={filters.email} onChange={e=>set("email",e.target.value)}/>
        <select className={ui.input} value={filters.examMode} onChange={e=>set("examMode",e.target.value)}><option value="">All exams</option><option>NEET</option><option>JEE</option><option>Both</option></select><select className={ui.input} value={filters.plan} onChange={e=>set("plan",e.target.value)}><option value="">All plans</option><option>Free</option><option>Premium</option></select>
        <select className={ui.input} value={filters.followUpStatus} onChange={e=>set("followUpStatus",e.target.value)}><option value="">All follow-ups</option><option>Unassigned</option>{statuses.map(s=><option key={s}>{s}</option>)}</select>
        {!employeeAccount?<select className={ui.input} value={filters.employeeId} onChange={e=>set("employeeId",e.target.value)}><option value="">All employees</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:null}<input className={ui.input} type="date" value={filters.from} onChange={e=>set("from",e.target.value)}/><input className={ui.input} type="date" value={filters.to} onChange={e=>set("to",e.target.value)}/><button className={cn(ui.buttonBase,ui.buttonPrimary)} type="submit">Apply filters</button>
      </form>
    </section>
    <section className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-[1250px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr>{["User Name","Mobile","Email","Device","Exam Mode","Plan","Created","Last Login","Follow-Up","Actions"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{items.map(u=><tr key={u.id}><td className="px-4 py-3 font-bold">{u.name||"Unnamed"}</td><td className="px-4 py-3">{u.mobile||"—"}</td><td className="px-4 py-3">{u.email||"—"}</td><td className="px-4 py-3">{u.deviceName}</td><td className="px-4 py-3">{u.examMode||"—"}</td><td className="px-4 py-3">{u.isPremium?"Premium":"Free"}</td><td className="px-4 py-3">{fmt(u.createdAt)}</td><td className="px-4 py-3">{fmt(u.lastLoginAt)}</td><td className="px-4 py-3">{u.followUp?<><b>{u.followUp.status}</b><div className="text-xs text-slate-500">{u.followUp.assignedEmployee?.employeeName}</div></>:"Unassigned"}</td><td className="px-4 py-3"><div className="flex gap-2"><button className={cn(ui.buttonBase,ui.buttonSecondary)} onClick={()=>setDetail(u)}>View</button>{employeeAccount?(u.followUp?<span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Assigned to you</span>:<button className={cn(ui.buttonBase,ui.buttonPrimary)} onClick={()=>void assign(u)}>Assign to me</button>):<button className={cn(ui.buttonBase,ui.buttonPrimary)} onClick={()=>setAssigning(u)}>{u.followUp?"Reassign":"Add to Follow-Up"}</button>}</div></td></tr>)}{!loading&&!items.length?<tr><td colSpan="10" className="p-8 text-center text-slate-500">No users match these filters.</td></tr>:null}</tbody></table></section>
    <div className="flex justify-between text-sm"><span>{meta.total||0} users</span><div className="flex gap-2"><button disabled={meta.page<=1} className={cn(ui.buttonBase,ui.buttonSecondary)} onClick={()=>{const n={...filters,page:meta.page-1};setFilters(n);void load(n)}}>Previous</button><button disabled={meta.page>=meta.totalPages} className={cn(ui.buttonBase,ui.buttonSecondary)} onClick={()=>{const n={...filters,page:meta.page+1};setFilters(n);void load(n)}}>Next</button></div></div>
    {!employeeAccount&&assigning?<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6"><h2 className="text-xl font-black">Assign {assigning.name||"user"}</h2><p className="my-4 text-sm text-slate-500">Choose the employee responsible for this follow-up.</p><select className={ui.input} defaultValue="" onChange={e=>void assign(assigning,e.target.value)}><option value="" disabled>Select employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name} — {x.email}</option>)}</select><button className={cn(ui.buttonBase,ui.buttonSecondary,"mt-4")} onClick={()=>setAssigning(null)}>Cancel</button></div></div>:null}
    {detail?<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><div className="mx-auto mt-10 max-w-3xl rounded-xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Complete User Profile</h2><button onClick={()=>setDetail(null)}>✕</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Name",detail.name],["Mobile",detail.mobile],["Email",detail.email],["Address",[detail.address,detail.city,detail.state,detail.country].filter(Boolean).join(", ")],["Device",detail.deviceName],["Exam mode",detail.examMode],["Level",detail.level],["Plan",detail.isPremium?`Premium${detail.premiumExpiresAt?` until ${fmt(detail.premiumExpiresAt)}`:""}`:"Free"],["Created",fmt(detail.createdAt)],["Last login",fmt(detail.lastLoginAt)],["Assigned employee",detail.followUp?.assignedEmployee?.employeeName||"Unassigned"],["Follow-up status",detail.followUp?.status||"Not added"]].map(([k,v])=><div key={k} className="rounded-lg bg-slate-50 p-3"><div className="text-xs font-bold uppercase text-slate-500">{k}</div><div className="mt-1">{v||"—"}</div></div>)}</div></div></div>:null}
  </div>;
}
